const SUPABASE_URL='https://efwfsiqkuydxbeaepvfx.supabase.co';
const SUPABASE_KEY='sb_publishable_Y8jB6u25p81qBWbrvbwOMA_1Zbfd-3Z';
const TEAM_ID='00000000-0000-4000-8000-000000000001';
const SESSION_KEY='finn.session';
const state={session:null,user:null,profile:null,clips:[],view:'feed',search:'',busy:false,error:'',notice:''};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isExtension=location.protocol.startsWith('chrome-extension')||location.protocol.startsWith('moz-extension');
const store={async get(k){if(globalThis.chrome?.storage?.local)return (await chrome.storage.local.get(k))[k];try{return JSON.parse(localStorage.getItem(k))}catch{return null}},async set(k,v){if(globalThis.chrome?.storage?.local)return chrome.storage.local.set({[k]:v});localStorage.setItem(k,JSON.stringify(v))},async remove(k){if(globalThis.chrome?.storage?.local)return chrome.storage.local.remove(k);localStorage.removeItem(k)}};
async function request(path,{method='GET',body,auth=true,headers={}}={}){const h={apikey:SUPABASE_KEY,'Content-Type':'application/json',...headers};if(auth&&state.session?.access_token)h.Authorization=`Bearer ${state.session.access_token}`;const r=await fetch(SUPABASE_URL+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||`Request failed (${r.status})`);return data}
async function saveSession(s){state.session=s;await store.set(SESSION_KEY,s)}
async function refresh(){if(!state.session?.refresh_token)return false;try{const s=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:state.session.refresh_token},auth:false});await saveSession(s);return true}catch{await signOut();return false}}
async function currentUser(){if(!state.session?.access_token)return null;try{return await request('/auth/v1/user')}catch(e){if(await refresh())return request('/auth/v1/user');throw e}}
async function boot(){state.session=await store.get(SESSION_KEY);captureTokensFromUrl();if(state.session){try{state.user=await currentUser();await loadWorkspace();await flushOutbox()}catch(e){state.error=e.message}}render()}
function captureTokensFromUrl(){const p=new URLSearchParams(location.hash.slice(1));if(p.get('access_token')){saveSession({access_token:p.get('access_token'),refresh_token:p.get('refresh_token'),expires_in:Number(p.get('expires_in')||3600),token_type:'bearer'});history.replaceState(null,'',location.pathname);}}
async function requestOtp(email,name){await request('/auth/v1/otp',{method:'POST',auth:false,body:{email,create_user:true,data:{display_name:name||email.split('@')[0]}}});state.notice='Check your email. Enter the 6-digit code, or paste the complete sign-in link.';render()}
async function verifyOtp(email,value){value=value.trim();let body={email,token:value,type:'email'};if(value.includes('token_hash=')||value.includes('token=')){const u=new URL(value);body={token_hash:u.searchParams.get('token_hash')||u.searchParams.get('token'),type:u.searchParams.get('type')||'email'}}else if(value.includes('access_token=')){const u=new URL(value);const p=new URLSearchParams(u.hash.slice(1));await saveSession({access_token:p.get('access_token'),refresh_token:p.get('refresh_token'),token_type:'bearer',expires_in:Number(p.get('expires_in')||3600)});state.user=await currentUser();await loadWorkspace();return render()}const s=await request('/auth/v1/verify',{method:'POST',auth:false,body});await saveSession(s);state.user=s.user||await currentUser();await loadWorkspace();render()}
async function signOut(){try{if(state.session)await request('/auth/v1/logout',{method:'POST'})}catch{}await store.remove(SESSION_KEY);state.session=state.user=state.profile=null;state.clips=[];render()}
async function loadWorkspace(){state.user=state.user||await currentUser();const [profiles,clips]=await Promise.all([request(`/rest/v1/profiles?id=eq.${state.user.id}&select=*`),request(`/rest/v1/clips?team_id=eq.${TEAM_ID}&select=*,profiles(display_name,initials),clip_pins(user_id)&order=created_at.desc`)]);state.profile=profiles?.[0]||{display_name:state.user.email?.split('@')[0]||'Member',initials:'TM'};state.clips=(clips||[]).map(c=>({...c,pinned:(c.clip_pins||[]).some(p=>p.user_id===state.user.id)}));}
async function flushOutbox(){const items=await store.get('finn.outbox')||[];if(!items.length)return;for(const item of items){try{await createClip(item)}catch{return}}await store.remove('finn.outbox');state.notice=`Synced ${items.length} saved browser capture${items.length===1?'':'s'}.`;await loadWorkspace()}
async function createClip(c){await request('/rest/v1/clips',{method:'POST',headers:{Prefer:'return=minimal'},body:{team_id:TEAM_ID,author_id:state.user.id,kind:c.kind,title:c.title||'Untitled',content:c.content||'',note:c.note||'',url:c.url||'',source_title:c.source_title||'',tags:c.tags||[],visibility:c.visibility||'team'}})}
async function saveCapture(e){e.preventDefault();const f=new FormData(e.target);const c={kind:f.get('content')?'quote':f.get('url')?'page':'note',title:f.get('title'),content:f.get('content'),note:f.get('note'),url:f.get('url'),source_title:f.get('source_title'),tags:String(f.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),visibility:f.get('visibility')};await createClip(c);state.notice='Saved to FINN.';state.view='feed';await loadWorkspace();render()}
async function togglePin(id,on){if(on){const r=await fetch(`${SUPABASE_URL}/rest/v1/clip_pins?clip_id=eq.${id}&user_id=eq.${state.user.id}`,{method:'DELETE',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session.access_token}`}});if(!r.ok)throw new Error('Could not unpin this clip.')}else await request('/rest/v1/clip_pins',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{clip_id:id,user_id:state.user.id}});await loadWorkspace();render()}
async function deleteClip(id){if(!confirm('Delete this clip?'))return;await fetch(`${SUPABASE_URL}/rest/v1/clips?id=eq.${id}`,{method:'DELETE',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session.access_token}`}});await loadWorkspace();render()}
async function addMember(e){e.preventDefault();const email=new FormData(e.target).get('email').toLowerCase().trim();await request('/rest/v1/allowed_emails',{method:'POST',headers:{Prefer:'return=minimal'},body:{email,role:'member',added_by:state.user.id}});state.notice=`${email} can now join FINN.`;e.target.reset();render()}
async function removeMember(email){await fetch(`${SUPABASE_URL}/rest/v1/allowed_emails?email=eq.${encodeURIComponent(email)}`,{method:'DELETE',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session.access_token}`}});state.notice=`Removed ${email}.`;await settings();}
async function settings(){state.view='settings';try{state.allowlist=await request('/rest/v1/allowed_emails?select=email,role,created_at&order=created_at.asc')}catch{state.allowlist=[]}render()}
async function activePage(){if(!globalThis.chrome?.tabs?.query)return{title:'',url:'',selection:''};const [t]=await chrome.tabs.query({active:true,currentWindow:true});let selection='';if(t?.id&&t.url?.startsWith('http'))try{const [r]=await chrome.scripting.executeScript({target:{tabId:t.id},func:()=>getSelection()?.toString()||''});selection=r?.result||''}catch{}return{title:t?.title||'',url:t?.url||'',selection}}
function authView(){return `<main class="auth"><div class="brand"><b>F</b><span>FINN</span></div><section class="authcard"><p class="eyebrow">RAHAR TEAM WORKSPACE</p><h1>Keep useful work close.</h1><p class="muted">Sign in with an approved team email. Rahul is already approved as the workspace owner.</p>${state.error?`<div class="error">${esc(state.error)}</div>`:''}${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}<form id="otpRequest"><label>Name<input name="name" placeholder="Your name"></label><label>Email<input name="email" type="email" required placeholder="you@company.com"></label><button>Send sign-in code</button></form><form id="otpVerify" class="verify"><label>Email<input name="email" type="email" required placeholder="Same approved email"></label><label>Code or sign-in link<input name="token" required placeholder="6-digit code or paste link"></label><button>Verify and enter FINN</button></form><small>Only emails approved by the FINN owner can join. Maximum 10 members.</small></section></main>`}
const icon=(name)=>name==='pin'?'◆':name==='copy'?'□':name==='link'?'↗':'•';
function card(c){const text=[c.title,c.content,c.note,c.source_title,(c.tags||[]).join(' ')].join(' ').toLowerCase();if(state.search&&!text.includes(state.search.toLowerCase()))return'';if(state.view==='pinned'&&!c.pinned)return'';return `<article class="clip"><header><span class="avatar">${esc(c.profiles?.initials||'TM')}</span><div><b>${esc(c.profiles?.display_name||'Teammate')}</b><small>${new Date(c.created_at).toLocaleString()} · ${c.visibility==='private'?'Only me':'Team'}</small></div><button data-pin="${c.id}" data-on="${c.pinned}">${icon('pin')}</button></header><p class="kind">${esc(c.kind).toUpperCase()}${c.source_title?` · ${esc(c.source_title)}`:''}</p><h3>${esc(c.title)}</h3>${c.content?`<blockquote>${esc(c.content)}</blockquote>`:''}${c.note?`<p>${esc(c.note)}</p>`:''}<div class="tags">${(c.tags||[]).map(t=>`<span>#${esc(t)}</span>`).join('')}</div><footer>${c.url?`<a href="${esc(c.url)}" target="_blank">Open source ↗</a>`:'<span></span>'}<span><button data-copy="${esc(c.content||c.note||c.url||c.title)}">Copy</button>${c.author_id===state.user.id?`<button class="danger" data-delete="${c.id}">Delete</button>`:''}</span></footer></article>`}
function shell(content){return `<div class="app"><aside><div class="brand"><b>F</b><span>FINN</span></div><nav><button data-view="feed" class="${state.view==='feed'?'active':''}">Team feed</button><button data-view="pinned" class="${state.view==='pinned'?'active':''}">Pinned</button><button data-view="capture" class="${state.view==='capture'?'active':''}">Capture</button><button id="settings" class="${state.view==='settings'?'active':''}">Team settings</button></nav><div class="account"><span class="avatar">${esc(state.profile?.initials||'TM')}</span><div><b>${esc(state.profile?.display_name)}</b><small>${esc(state.user?.email)}</small></div></div></aside><main class="content">${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}${state.error?`<div class="error">${esc(state.error)}</div>`:''}${content}</main></div>`}
function feedView(){const title=state.view==='pinned'?'Pinned':'Team feed';return shell(`<header class="top"><div><p class="eyebrow">RAHAR · FINN</p><h1>${title}</h1></div><button data-view="capture">+ Capture</button></header><div class="search"><input id="search" value="${esc(state.search)}" placeholder="Search clips, notes, sources, tags…"></div><section class="grid">${state.clips.map(card).join('')||'<div class="empty">Nothing here yet. Capture something worth keeping.</div>'}</section>`)}
async function captureView(){const p=await activePage();return shell(`<header class="top"><div><p class="eyebrow">QUICK CAPTURE</p><h1>Keep what matters.</h1></div></header><form id="capture" class="form"><label>Title<input name="title" required value="${esc(p.selection?p.selection.slice(0,90):p.title)}" placeholder="What did you find?"></label>${p.selection?`<label>Selected text<textarea name="content" rows="4">${esc(p.selection)}</textarea></label>`:'<input type="hidden" name="content" value="">'}<label>Note<textarea name="note" rows="4" placeholder="Why is this useful for your team?"></textarea></label><label>Source URL<input name="url" value="${esc(p.url)}"></label><input type="hidden" name="source_title" value="${esc(p.title)}"><div class="row"><label>Tags<input name="tags" placeholder="research, design"></label><label>Visibility<select name="visibility"><option value="team">Team</option><option value="private">Only me</option></select></label></div><button>Save to FINN</button></form>`)}
function settingsView(){const list=(state.allowlist||[]).map(x=>`<li><span><b>${esc(x.email)}</b><small>${esc(x.role)}</small></span>${x.role!=='owner'?`<button data-remove="${esc(x.email)}">Remove</button>`:''}</li>`).join('');return shell(`<header class="top"><div><p class="eyebrow">WORKSPACE</p><h1>Team settings</h1></div><button id="signout" class="secondary">Sign out</button></header><section class="panel"><h2>Approved members</h2><p class="muted">Add an email before that teammate requests a sign-in code. FINN accepts at most 10 approved members.</p><form id="member" class="inline"><input name="email" type="email" required placeholder="teammate@example.com"><button>Add member</button></form><ul class="members">${list||'<li>You do not have permission to view the allowlist.</li>'}</ul></section><section class="panel"><h2>Connection</h2><p>Supabase project <code>efwfsiqkuydxbeaepvfx</code> · Mumbai region · Row Level Security enabled.</p></section>`)}
async function render(){const root=$('#root');if(!root)return;if(!state.session||!state.user){root.innerHTML=authView();bind();return}if(state.view==='capture')root.innerHTML=await captureView();else if(state.view==='settings')root.innerHTML=settingsView();else root.innerHTML=feedView();bind()}
function go(view){state.view=view;state.notice='';render()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#settings')&&($('#settings').onclick=settings);$('#signout')&&($('#signout').onclick=signOut);$('#search')&&($('#search').oninput=e=>{state.search=e.target.value;document.querySelector('.grid').innerHTML=state.clips.map(card).join('')||'<div class="empty">No matches.</div>';bindCards()});$('#otpRequest')&&($('#otpRequest').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await requestOtp(f.get('email').toLowerCase().trim(),f.get('name'))}catch(x){state.error=x.message;render()}});$('#otpVerify')&&($('#otpVerify').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await verifyOtp(f.get('email').toLowerCase().trim(),f.get('token'))}catch(x){state.error=x.message;render()}});$('#capture')&&($('#capture').onsubmit=async e=>{try{await saveCapture(e)}catch(x){state.error=x.message;render()}});$('#member')&&($('#member').onsubmit=async e=>{try{await addMember(e)}catch(x){state.error=x.message;render()}});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeMember(b.dataset.remove));bindCards()}
function bindCards(){document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>togglePin(b.dataset.pin,b.dataset.on==='true'));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copied'});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteClip(b.dataset.delete))}
boot();
